@echo off
setlocal EnableExtensions

set "ROOT=%~dp0.."
set "VERSION="
for /f "usebackq delims=" %%v in ("%ROOT%\VERSION") do set "VERSION=%%v"
if not defined VERSION set "VERSION=0.1.0"

rem Regenerate src\Version.h from the VERSION file so the packaged .exe's
rem resource metadata always matches the zip name. The checked-in copy keeps
rem plain IDE builds working; this overwrite is what prevents drift.
set "VMAJOR="
set "VMINOR="
set "VPATCH="
for /f "tokens=1,2,3 delims=." %%a in ("%VERSION%") do (
    set "VMAJOR=%%a"
    set "VMINOR=%%b"
    set "VPATCH=%%c"
)
if not defined VMAJOR set "VMAJOR=0"
if not defined VMINOR set "VMINOR=0"
if not defined VPATCH set "VPATCH=0"
> "%ROOT%\src\Version.h" (
    echo #pragma once
    echo.
    echo // Release version numbers for VS_VERSION_INFO in LiteDDC.rc.
    echo // AUTO-GENERATED by tools\ship.cmd from the repo's VERSION file - do
    echo // not edit by hand; edit VERSION and re-ship instead.
    echo.
    echo #define LITEDDC_VERSION_MAJOR %VMAJOR%
    echo #define LITEDDC_VERSION_MINOR %VMINOR%
    echo #define LITEDDC_VERSION_PATCH %VPATCH%
    echo #define LITEDDC_VERSION_REVISION 0
)

set "OUTDIR=%ROOT%\releases"
if exist "%OUTDIR%" rmdir /s /q "%OUTDIR%"
mkdir "%OUTDIR%"

echo [LiteDDC] Packaging %VERSION% ...

rem Build x64
call "%~dp0build.cmd" Release x64
if errorlevel 1 goto failed

rem Build ARM64
call "%~dp0build.cmd" Release ARM64
if errorlevel 1 goto failed

rem Package x64
echo [LiteDDC] Creating x64 zip ...
mkdir "%OUTDIR%\LiteDDC-%VERSION%-x64"
copy "%ROOT%\bin\x64\Release\LiteDDC.exe" "%OUTDIR%\LiteDDC-%VERSION%-x64\" >nul
call :write_readme "%OUTDIR%\LiteDDC-%VERSION%-x64\README.txt"
tar -a -c -f "%OUTDIR%\LiteDDC-%VERSION%-x64.zip" -C "%OUTDIR%" "LiteDDC-%VERSION%-x64"
if errorlevel 1 goto failed
rmdir /s /q "%OUTDIR%\LiteDDC-%VERSION%-x64"

rem Package ARM64
echo [LiteDDC] Creating ARM64 zip ...
mkdir "%OUTDIR%\LiteDDC-%VERSION%-ARM64"
copy "%ROOT%\bin\ARM64\Release\LiteDDC.exe" "%OUTDIR%\LiteDDC-%VERSION%-ARM64\" >nul
call :write_readme "%OUTDIR%\LiteDDC-%VERSION%-ARM64\README.txt"
tar -a -c -f "%OUTDIR%\LiteDDC-%VERSION%-ARM64.zip" -C "%OUTDIR%" "LiteDDC-%VERSION%-ARM64"
if errorlevel 1 goto failed
rmdir /s /q "%OUTDIR%\LiteDDC-%VERSION%-ARM64"

echo.
echo [LiteDDC] Done! Zip files:
echo   %OUTDIR%\LiteDDC-%VERSION%-x64.zip
echo   %OUTDIR%\LiteDDC-%VERSION%-ARM64.zip
exit /b 0

:failed
echo [LiteDDC] Build failed.
exit /b 1

:write_readme
echo LiteDDC %VERSION%>"%~1"
echo =================>>"%~1"
echo.>>"%~1"
echo Monitor brightness/contrast/saturation control (DDC/CI) for Windows>>"%~1"
echo 10/11, living in the system tray - plus monitor speaker volume, R/G/B>>"%~1"
echo gain sliders, and NVIDIA Digital Vibrance where an NVIDIA display is>>"%~1"
echo present.>>"%~1"
echo.>>"%~1"
echo USAGE>>"%~1"
echo   Double-click LiteDDC.exe to start. It runs from the tray icon.>>"%~1"
echo   Scroll the mouse wheel while hovering the tray icon to adjust your>>"%~1"
echo   monitor(s). Right-click the icon for settings and Exit.>>"%~1"
echo.>>"%~1"
echo TROUBLESHOOTING>>"%~1"
echo   If no monitor is detected or controls do nothing, enable DDC/CI in>>"%~1"
echo   your monitor's on-screen display menu (often called "DDC/CI">>"%~1"
echo   or "OSD lockout/Control"). Some monitors ship with it disabled.>>"%~1"
echo.>>"%~1"
echo KNOWN LIMITATION>>"%~1"
echo   Laptop internal panels are not controllable (they use a different>>"%~1"
echo   backlight interface than DDC/CI). They are detected and excluded>>"%~1"
echo   automatically - external monitors only.>>"%~1"
echo.>>"%~1"
echo REQUIREMENTS>>"%~1"
echo   Windows 10 1809+ (x64) or Windows 11 (x64/ARM64). No runtime to install.>>"%~1"
echo.>>"%~1"
echo LICENSE>>"%~1"
echo   MIT License. See https://github.com/hmwassim/LiteDDC>>"%~1"
exit /b 0
