#pragma once

// Release version numbers for VS_VERSION_INFO in LiteDDC.rc.
// AUTO-GENERATED by tools\ship.cmd from the repo's VERSION file - do
// not edit by hand; edit VERSION and re-ship instead.

#define LITEDDC_VERSION_MAJOR 1
#define LITEDDC_VERSION_MINOR 0
#define LITEDDC_VERSION_PATCH 0
#define LITEDDC_VERSION_REVISION 0
